### PR TITLE
Struct polymorphism: fix member ordering

### PR DESCRIPTION
**Pull request by szbergeron**
Fixes an incorrect struct packing optimization that was causing event type to be misread

### CODE REVIEW

**Comment by szbergeron** [comment]
Not really sure why CI is failing on this one, windows log doesn't really have any info

**Comment by Et7f3** [comment]
@szbergeron Can you add this snippet https://github.com/microsoft/azure-pipelines-tasks/issues/9421#issuecomment-457374399

**Comment by szbergeron** [comment]
@Et7f3 add it where? Not sure what file that's talking about

**Comment by Et7f3** [comment]
In the CI config file https://github.com/revery-ui/esy-sdl2/blob/master/.ci/esy-build-steps.yml after the `npm install -g esy@0.5.8` step so when this step fail again we will have logs to debug.

**Comment by szbergeron** [comment]
@Et7f3 that would fail for non-windows platforms right? I see reference to C:\...

**Review by Et7f3 — APPROVED** [review]

**Comment by Et7f3** [comment]
Sorry for this :sweat_smile: I merge and thanks.

**Pull request merged**
