### PR TITLE
Fix build on Fedora37 

### LINKED ISSUE #21: Build fails with Wayland 1.20
```
      CC     build/SDL_virtualjoystick.lo
      CC     build/SDL_dummysensor.lo
      LTLINK build/libSDL2.la
    /usr/bin/ld: build/.libs/SDL_waylanddatamanager.o: in function `wl_data_offer_receive':
    SDL_waylanddatamanager.c:(.text+0x54): undefined reference to `wl_proxy_marshal_flags'
    /usr/bin/ld: build/.libs/SDL_waylanddatamanager.o: in function `wl_data_offer_destroy':
    SDL_waylanddatamanager.c:(.text+0x9f): undefined reference to `wl_proxy_marshal_flags'
    /usr/bin/ld: build/.libs/SDL_waylanddatamanager.o: in function `wl_data_source_offer':
    SDL_waylanddatamanager.c:(.text+0xf1): undefined reference to `wl_proxy_marshal_flags'
    /usr/bin/ld: build/.libs/SDL_waylanddatamanager.o: in function `wl_data_source_destroy':
    SDL_waylanddatamanager.c:(.text+0x138): undefined reference to `wl_proxy_marshal_flags'
    /usr/bin/ld: build/.libs/SDL_waylanddatamanager.o: in function `wl_data_device_set_selection':
    SDL_waylanddatamanager.c:(.text+0x193): undefined reference to `wl_proxy_marshal_flags'
    /usr/bin/ld: build/.libs/SDL_waylandevents.o:SDL_waylandevents.c:(.text+0xb1): more undefined references to `wl_proxy_marshal_flags' follow
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:154: build/libSDL2.la] Error 1
    error: command failed: 'bash' '-c' './build-scripts/esybuild.sh --os=linux' (exited with 2)
    esy-build-package: exiting with errors above...

  building esy-sdl2@2.0.14000
esy: exiting due to errors above
```

Upstream bug and fixing commit: 
https://github.com/libsdl-org/SDL/issues/5088
https://github.com/libsdl-org/SDL/commit/e2ade2bfc46d915cd306c63c830b81d800b2575f
The fix will probably be included in next release `2.0.19` where this project is still in version `2.0.14`

### PR DESCRIPTION
**Pull request by edwintorok**
Fixes https://github.com/revery-ui/esy-sdl2/issues/21

### CODE REVIEW

**Comment by edwintorok** [comment]
Upgrading to a new SDL2 seems complicated because this repo and original SDL2 do not share history so git can't figure out how to merge it, so I've cherry-picked just the 2 commits related to the wayland fix and it at least builds now.

**Comment by edwintorok** [comment]
Also related to https://github.com/revery-ui/revery/issues/1094

**Comment by Et7f3** [comment]
> do not share history so git can't figure out how to merge it

Yeah that unfortunate you still have date time to know around which commit it is.

**Comment by Et7f3** [comment]
Thanks for those I will try to update esy-sdl with git history so it is easier to track

**Comment by Et7f3** [comment]
Oops I rebased and we don't see you are the committer 😓

**Comment by Et7f3** [comment]
I began to reconcile the tree in this branch https://github.com/revery-ui/esy-sdl2/tree/git I haven't done history between 2.0.10 and 2.0.14. I will do another round to fix history between and will use it in revery.

**Pull request merged**
